import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Login.module.css'
import Background from '@/Components/Background'

const Login = () => {
  return (
    <div className={styles.login_form}>
      <Head>
        <title>Next + Figma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ------------------------------ Background ------------------------------ */}
      <Background />
      {/* ------------------------------ Background ------------------------------ */}

      {/* ------------------------------ Login Form ------------------------------ */}
      <div className={styles.login}>
        <div className={styles.head}>
          <p className={styles.head1}>Welcome Back!</p>
          <p className={styles.head2}>Sign In to your Account</p>
        </div>
        <form >
          <input className={styles.input_box} placeholder='Email' />
          <input className={styles.input_box} placeholder='Password' />
          <div className={styles.box}>
            <label className={styles.checkbox} name="Remember Me">
              <input type="checkbox" className={styles.checkbox_box} name="Remeber Me" />
              <p className={styles.checkbox_text}>Remeber Me</p>
            </label>
            <p className={styles.forgot}>Forgot Password?</p>
          </div>
          <div className={styles.button}></div>
          <button className={styles.button1}>Sign In</button>
          <button className={styles.button2}>
            <Image src="/Google.png" width="22" height="22"></Image>
            <p className={styles.btn}>Login with Google</p>
          </button>
          <div className={styles.account}>
            <p className={styles.signin}>Don’t have an account?</p>
            <Link href="/signin" className={styles.link}>Sign In</Link>
          </div>
        </form>
      </div>
      {/* ------------------------------ Login Form ------------------------------ */}

    </div>
  )
}

export default Login