import Head from 'next/head'
import styles from '@/styles/login.module.css'
import Image from 'next/image'

const Login = () => {
  return (
    <div>

      <Head>
        <title>Next + Figma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 
      <div className={styles.container}>
        <div className={styles.typography}>
          <p className={styles.head1}>Welcome Back!</p>
          <p className={styles.head2}>Sign In to your Account</p>
        </div>
        <form>

        </form>

      </div> */}


      <div className={styles.rectangle}>
        <div className={styles.pyxis}></div>
        <div className={styles.logo}></div>
        <div className={styles.text}>
          <p>Advanced Search-Find your smartest<br /> way to the buyer.</p>
          <p className={styles.subtext}>Start your company in minutes</p>
        </div>
      </div>


      {/* <Image className={styles.logo} src="/logo.png" width="64" height="65" ></Image> */}


      {/* <Image src="/Rectangle 7126.png" width="820" height="1200" ></Image> */}
    </div>
  )
}

export default Login